def get_weather_info(code: int):
    mapping = {
        0: ("clear-day", "Clear sky"),
        1: ("partly-cloudy-day", "Mainly clear"),
        2: ("partly-cloudy-day", "Partly cloudy"),
        3: ("cloudy", "Overcast"),
        45: ("fog", "Fog"),
        48: ("fog", "Depositing rime fog"),
        51: ("rain", "Drizzle: Light"),
        53: ("rain", "Drizzle: Moderate"),
        55: ("rain", "Drizzle: Dense"),
        56: ("sleet", "Freezing Drizzle: Light"),
        57: ("sleet", "Freezing Drizzle: Dense"),
        61: ("rain", "Rain: Slight"),
        63: ("rain", "Rain: Moderate"),
        65: ("rain", "Rain: Heavy"),
        66: ("sleet", "Freezing Rain: Light"),
        67: ("sleet", "Freezing Rain: Heavy"),
        71: ("snow", "Snow fall: Slight"),
        73: ("snow", "Snow fall: Moderate"),
        75: ("snow", "Snow fall: Heavy"),
        77: ("snow", "Snow grains"),
        80: ("rain", "Rain showers: Slight"),
        81: ("rain", "Rain showers: Moderate"),
        82: ("rain", "Rain showers: Violent"),
        85: ("snow", "Snow showers: Slight"),
        86: ("snow", "Snow showers: Heavy"),
        95: ("thunderstorm", "Thunderstorm: Slight or moderate"),
        96: ("thunderstorm", "Thunderstorm with slight hail"),
        99: ("thunderstorm", "Thunderstorm with heavy hail"),
    }
    return mapping.get(code, ("unknown", "Unknown"))
